### ISSUE TITLE
pisces on Window

### ISSUE THREAD

**Issue by rigotibi** [LANL-Seismoacoustics/pisces#37]
I used to run pisces on my Window machine using Python 2.6. Now I have upgraded to Python 3.7 and re-installed pisces.
The installation appeared to be successful but, when I do “import pisces” it is throwing errors like the one below.
I know you don't use Window; but, as the developer of pisces, do you know anyone who has successfully installed and run pisces on a Window machine with Python 3.8 and could help me with this?

------------------------------------
                File "<ipython-input-12-46ea4422578a>", line 1, in <module>
                import pisces
 
                File "\\snl\home\rtibi\Software\PiscesWindows\pisces-piscesWindows\pisces-piscesWindows\pisces\__init__.py", line 24, in <module>
                from pisces.io.trace import wfdisc2trace
 
                File "C:\Users\rtibi\AppData\Local\Continuum\anaconda3\lib\site-packages\pisces-0.3.2-py3.7.egg\pisces\io\trace.py", line 7, in <module>
                from pisces.io.readwaveform import read_waveform
 
                File "C:\Users\rtibi\AppData\Local\Continuum\anaconda3\lib\site-packages\pisces-0.3.2-py3.7.egg\pisces\io\readwaveform.py", line 15, in <module>
                libecomp = C.CDLL(os.path.dirname(__file__) + '/lib/libecompression' + ext)
 
                File "C:\Users\rtibi\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 356, in __init__
                self._handle = _dlopen(self._name, mode)
 
OSError: [WinError 126] The specified module could not be found

**Comment by jkmacc-LANL** [comment]
Hi @rigotibi !  Thanks for posting an issue here.

Your version is trying to load C-libraries that it can't compile/link properly.  Oddly, though, it looks like you're running Pisces v0.3.2, but Pisces > v0.3.1 has removed these libraries.  How are you installing Pisces?  From PyPI?  It *should* have the C-libraries removed in v0.3.2.  Do you have e1 data, such that you need those?

**Comment by jkmacc-LANL** [comment]
@rigotibi , if you don't want to have pip install the `e1` module, just type `pip install pisces` or if you've cloned the repo, `pip install .`.  You should only get the `e1` module if you `pip install pisces[e1]`.  You may need to clean any previous Pisces installations (`pip uninstall pisces`) or build directories (`./build`) by either manually deleting them or running `python setup.py clean --all`.

Also, since you're a Windows user, you may be able to help with this [e1 issue](https://github.com/LANL-Seismoacoustics/e1/issues/1) .  If you or a colleague who knows Windows, C, Python, etc., I'd love some feedback on [this PR](https://github.com/LANL-Seismoacoustics/e1/pull/2) on the e1 project.  It just tries to automatically install the "e1" package and run a quick e1 decompression test.  I just don't know much about linking to C libraries on a Windows machine.

**Comment by jkmacc-LANL** [comment]
If you need to connect to an Oracle database, you will need to install `cx_oracle` and the associated "instantclient" libraries.  I'm on a Mac, so I've found some "conda" channels that have these libraries bundled already for Mac. I'm not sure about Windows.

**Comment by jkmacc-LANL** [comment]
@rigotibi This was fixed in LANL-Seismoacoustics/e1#3 .  Thanks again to @byoung4!
